dataset_name: mnist
iid: True
seed: 42
num_clients: 6
timeslots: 20
arrival_rate:
  type: constant
  quantity: 100
cache_capacity: 
  type: constant
  quantity: 500
fl_rounds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
policies: random
model_name: mnist_conv
topology: none