dataset_name: mnist
num_classes: 10
iid: False
iid_score: 10
seed: 42
num_clients: 9
timeslots: 50
arrival_rate:
  type: constant
  quantity: 100
cache_capacity: 
  type: constant
  quantity: 500000
fl_rounds: 
  type: all
  freq: 1
policies: sfifo
max_resources: 100000 # each client can process 1000 samples at max
resources:
  placeholder: none
  # 0: "first-half"
model_name: mnist_conv
topology: none
optimal_data_sharing:
  topology: "ring"
  edge_capacity: 1000
  multi-timeslot: False
