dataset_name: mnist
iid: False
seed: 42
num_clients: 6
timeslots: 70
arrival_rate:
  type: constant
  quantity: 100
cache_capacity: 
  type: constant
  quantity: 500
fl_rounds: 
  type: all
  freq: 1
policies: random
max_resources: 1000 # each client can process 1000 samples at max
resources:
  # placeholder: none
  0: "first-half"
model_name: mnist_conv
topology: ring